### ISSUE TITLE
Some benchmarks missing after PR #33

### ISSUE THREAD

**Issue by siddharth-krishna** [open-energy-transition/solver-benchmark#36]
This is the plot of all benchmarks at commit `77312c1` (before PR #33):
<img width="754" alt="image" src="https://github.com/user-attachments/assets/581ee203-0ab4-47d7-b59d-19a31d4bc808">

And this is the plot at commit `a067763`, after #33, when no filters have been modified:
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/89ccf361-9f87-448a-818a-3f9e58ecdf43">

The second plot is missing all the OK data points for solvers other than Gurobi. What happened to them?

**Comment by jacek-oet** [comment]
@siddharth-krishna We have different names between the metadata and the benchmark results
eg:
pypsa-wind+sol+ely-1h-ucwind
pypsa-gas+wind+sol+ely-1h-ucgas:

pypsa-wind+sol+ely-1h
pypsa-gas+wind+sol+ely-1h

**Comment by jacek-oet** [comment]
The second plot is missing all the OK data points for solvers other than Gurobi. What happened to them? 
We have different names between the metadata and the benchmark results
eg:
pypsa-wind+sol+ely-1h-ucwind
pypsa-gas+wind+sol+ely-1h-ucgas:

pypsa-wind+sol+ely-1h
pypsa-gas+wind+sol+ely-1h

Could we use the same name?

Meta-data
![image](https://github.com/user-attachments/assets/a9633a23-8d34-4d3f-bea9-bf2a8f5e4f92)
benchmark_results.csv
![image](https://github.com/user-attachments/assets/8bf79d73-dd72-4ccb-a86a-a20b70b8388e)

**Comment by danielelerede-oet** [comment]
@jacek-oet there have been some changes to the problems (not only concerning their names, actually). I'm reporting here the old name and the corresponding new one for those which have changed, but please tell me if I can make more direct modifications:

|*Old*|*New*|
|--|--|
|pypsa-wind+sol+ely-1h-ucwind|pypsa-gas+wind+sol+ely-1h-ucgas|
|pypsa-wind+sol+ely-1h|pypsa-gas+wind+sol+ely-1h|

**Comment by siddharth-krishna** [comment]
@jacek-oet could we add a quick assertion or test to check for such errors?

**Comment by jacek-oet** [comment]
> please tell me if I can make more direct modifications

We defined benchmark_files_info in `runner/run_benchmarks.py` (see the attached image). This configuration is used to generate the Benchmark field in the CSV files (`benchmark_results.csv` and `benchmark_results_mean_stddev.csv`) when we run `run_benchmarks.py`.
![image](https://github.com/user-attachments/assets/b27cb629-892c-4486-864e-723a7427e4e3)


Currently, if a benchmark name is changed, we need to update both the meta-data and `runner/run_benchmarks.py`, then re-run the script. If we do not re-run it, we must manually update `benchmark_results.csv` and `benchmark_results_mean_stddev.csv`.

I believe we could streamline this process by using the meta-data for `benchmark_files_info` instead of having it defined in `runner/run_benchmarks.py`.

> could we add a quick assertion or test to check for such errors?

Yes, I think we should add a unit test to check for such errors.

**Comment by siddharth-krishna** [comment]
@jacek-oet could you please make a quick fix of this, I need the website working for a presentation I'm giving at 1pm UTC-4 on Friday. 🙏 

And you're right, once we figure out the CI/Dockerfile for generating benchmarks, we should upload them in a GCP bucket and change the `url`s. At this point it will be good to move the stuff in `run_benchmarks.py` to the benchmarks metadata file, like you suggested.
